### ISSUE TITLE
'devise_for' directive in routes.rb gives 'relation "users" does not exist' error

### ISSUE THREAD

**Issue by gencer** [TalentBox/sequel-rails#144]
`devise_for` directive in `routes.rb` gives `relation "users" does not exist` error.

When I try to load database via `db:schema:load` command, If routes.rb have this lines (or equivalent):

```
 devise_for :users, .. controllers: {
      sessions......
       ...
  }...
```
then I get `PG::UndefinedTable: ERROR:  relation "users" does not exist` error. If I remove that devise_for directive then everything works perfectly. This behavior made our deployment on new machines painful.

Something is triggering deivse OR sequel before load happens.

Ruby 2.4.2 on Windows (and linux) with latest version of devise, seqyuel (5.2) and Sequel-Rails used.

**Trace:**
```
Caused by:
PG::UndefinedTable: ERROR:  relation "users" does not exist
LINE 1: SELECT * FROM "users" LIMIT 1
                      ^
D:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/rack-mini-profiler-0.10.6/lib/patches/db/pg.rb:90:in `async_exec'
D:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/rack-mini-profiler-0.10.6/lib/patches/db/pg.rb:90:in `async_exec'
D:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/sequel-5.2.0/lib/sequel/adapters/postgres.rb:145:in `block in execute_query'
D:/Ruby24-x64/lib/ruby/gems/2.4.0/bundler/gems/sequel-rails-3fe1f449c968/lib/sequel_rails/sequel/database/active_support_notification.rb:17:in `block in log_connection_yield'
D:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/activesupport-5.1.4/lib/active_support/notifications.rb:166:in `block in instrument'
D:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/activesupport-5.1.4/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
D:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/activesupport-5.1.4/lib/active_support/notifications.rb:166:in `instrument'
D:/Ruby24-x64/lib/ruby/gems/2.4.0/bundler/gems/sequel-rails-3fe1f449c968/lib/sequel_rails/sequel/database/active_support_notification.rb:11:in `log_connection_yield'
D:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/sequel-5.2.0/lib/sequel/adapters/postgres.rb:145:in `execute_query'
D:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/sequel-5.2.0/lib/sequel/adapters/postgres.rb:133:in `block in execute'
D:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/sequel-5.2.0/lib/sequel/adapters/postgres.rb:109:in `check_disconnect_errors'
D:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/sequel-5.2.0/lib/sequel/adapters/postgres.rb:133:in `execute'
D:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/sequel-5.2.0/lib/sequel/adapters/postgres.rb:449:in `_execute'
D:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/sequel-5.2.0/lib/sequel/adapters/postgres.rb:273:in `block (2 levels) in execute'
D:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/sequel-5.2.0/lib/sequel/adapters/postgres.rb:471:in `check_database_errors'
D:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/sequel-5.2.0/lib/sequel/adapters/postgres.rb:273:in `block in execute'
D:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/sequel-5.2.0/lib/sequel/database/connecting.rb:264:in `block in synchronize'
D:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/sequel-5.2.0/lib/sequel/connection_pool/threaded.rb:87:in `hold'
D:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/sequel-5.2.0/lib/sequel/database/connecting.rb:264:in `synchronize'
D:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/sequel-5.2.0/lib/sequel/adapters/postgres.rb:273:in `execute'
D:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/sequel-5.2.0/lib/sequel/dataset/actions.rb:1085:in `execute'
D:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/sequel-5.2.0/lib/sequel/adapters/postgres.rb:559:in `fetch_rows'
D:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/sequel-5.2.0/lib/sequel/dataset/actions.rb:151:in `each'
D:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/sequel-5.2.0/lib/sequel/dataset/actions.rb:85:in `columns!'
D:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/sequel-5.2.0/lib/sequel/dataset/actions.rb:75:in `columns'
D:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/sequel-5.2.0/lib/sequel/model/base.rb:242:in `columns'
D:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/sequel-5.2.0/lib/sequel/model/base.rb:802:in `block (2 levels) in get_db_schema'
D:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/sequel-5.2.0/lib/sequel/model/base.rb:718:in `block in check_non_connection_error'
D:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/sequel-5.2.0/lib/sequel/database/transactions.rb:151:in `block in transaction'
D:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/sequel-5.2.0/lib/sequel/database/connecting.rb:264:in `block in synchronize'
D:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/sequel-5.2.0/lib/sequel/connection_pool/threaded.rb:91:in `hold'
D:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/sequel-5.2.0/lib/sequel/database/connecting.rb:264:in `synchronize'
D:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/sequel-5.2.0/lib/sequel/database/transactions.rb:145:in `transaction'
D:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/sequel-5.2.0/lib/sequel/model/base.rb:718:in `check_non_connection_error'
D:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/sequel-5.2.0/lib/sequel/model/base.rb:802:in `block in get_db_schema'
D:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/sequel-5.2.0/lib/sequel/model/base.rb:835:in `get_db_schema'
D:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/sequel-5.2.0/lib/sequel/model/base.rb:637:in `set_dataset'
D:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/sequel-5.2.0/lib/sequel/model/base.rb:492:in `inherited'
D:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/sequel-5.2.0/lib/sequel/plugins/subclasses.rb:70:in `inherited'
D:/testapp/web/app/models/user.rb:1:in `<top (required)>'
D:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:476:in `load'
D:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:476:in `block in load_file'
D:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:661:in `new_constants_in'
D:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:475:in `load_file'
D:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:374:in `block in require_or_load'
D:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:36:in `block in load_interlock'
D:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies/interlock.rb:12:in `block in loading'
D:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/activesupport-5.1.4/lib/active_support/concurrency/share_lock.rb:149:in `exclusive'
```

**Comment by gencer** [comment]
There is a workaround for this issue (as far as I discover):

wrap `devise_for` directive with:

```
if Sequel::Model.db.table_exists?(:users)
    devise_for ...
end
```

This will make sure that `devise_for` directive only run after `:users` table gets loaded successfully. So, schema load will work, frontend also will work too.

It seems, User model and devise gets loaded just before hooks runs. They should be delayed.

**Comment by cmrd-senya** [comment]
I confirm the issue and the workaround

**Comment by a0s** [comment]
I have permanent `Sequel::Error: No database associated with Sequel::Model: have you called Sequel.connect or Sequel::Model.db=` during rake db:drop/create/migrate. So, my variant of workaround:
```ruby
  unless Rake.application.top_level_tasks.present?
    devise_for :users
  end
```
