### ISSUE TITLE
Multi DB with SequelRails (issues and possible solution way)

### ISSUE THREAD

**Issue by gencer** [TalentBox/sequel-rails#168]
When multiple databases used with Sequel' s internal system, SequelRails tries to log connection and using this connection for all models even if model belongs to another connection.

## Problem

SequelRails has an ActiveSupport Notification instrument. When anything goes to this, primary (default) connection is used for all models regardless which model belongs to which connection.

See below stack trace. You will see that `emails` table does not exists. It's because SequelRails executes this in primary database which has no `emails` table. When I debug line-by-line, I see that conn value is my primary database and not secondary.

## How I solved this?

Not quite correct but commenting/removing this line: https://github.com/TalentBox/sequel-rails/blob/master/lib/sequel_rails/sequel/database/active_support_notification.rb#L21
 solves my problem. Simply I tell SequelRails to only log but not raise error.

## Question.

Do you have any other idea how we can overcome on this? Monkey-patch using `lib/` dir or any other idea?

**Stack error:**
```
I, [2018-12-24T15:27:23.097385 #6287]  INFO -- : Refreshing Gem list
Sequel::DatabaseError: PG::UndefinedTable: ERROR:  relation "emails" does not exist
LINE 1: SELECT * FROM "emails" LIMIT 1
                      ^
  /disk5/www/gb/box/shared/bundle/ruby/2.5.0/gems/sequel-5.15.0/lib/sequel/adapters/postgres.rb:152:in `async_exec'
  /disk5/www/gb/box/shared/bundle/ruby/2.5.0/gems/sequel-5.15.0/lib/sequel/adapters/postgres.rb:152:in `block in execute_query'
  /disk5/www/gb/box/shared/bundle/ruby/2.5.0/gems/sequel-rails-1.0.1/lib/sequel_rails/sequel/database/active_support_notification.rb:17:in `block in log_connection_yield'
  /disk5/www/gb/box/shared/bundle/ruby/2.5.0/gems/activesupport-5.2.2/lib/active_support/notifications.rb:168:in `block in instrument'
  /disk5/www/gb/box/shared/bundle/ruby/2.5.0/gems/activesupport-5.2.2/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
  /disk5/www/gb/box/shared/bundle/ruby/2.5.0/gems/activesupport-5.2.2/lib/active_support/notifications.rb:168:in `instrument'
  /disk5/www/gb/box/shared/bundle/ruby/2.5.0/gems/sequel-rails-1.0.1/lib/sequel_rails/sequel/database/active_support_notification.rb:11:in `log_connection_yield'
  /disk5/www/gb/box/shared/bundle/ruby/2.5.0/gems/sequel-5.15.0/lib/sequel/adapters/postgres.rb:152:in `execute_query'
  /disk5/www/gb/box/shared/bundle/ruby/2.5.0/gems/sequel-5.15.0/lib/sequel/adapters/postgres.rb:140:in `block in execute'
  /disk5/www/gb/box/shared/bundle/ruby/2.5.0/gems/sequel-5.15.0/lib/sequel/adapters/postgres.rb:116:in `check_disconnect_errors'
  /disk5/www/gb/box/shared/bundle/ruby/2.5.0/gems/sequel-5.15.0/lib/sequel/adapters/postgres.rb:140:in `execute'
  /disk5/www/gb/box/shared/bundle/ruby/2.5.0/gems/sequel-5.15.0/lib/sequel/adapters/postgres.rb:496:in `_execute'
  /disk5/www/gb/box/shared/bundle/ruby/2.5.0/gems/sequel-5.15.0/lib/sequel/adapters/postgres.rb:314:in `block (2 levels) in execute'
  /disk5/www/gb/box/shared/bundle/ruby/2.5.0/gems/sequel-5.15.0/lib/sequel/adapters/postgres.rb:518:in `check_database_errors'
  /disk5/www/gb/box/shared/bundle/ruby/2.5.0/gems/sequel-5.15.0/lib/sequel/adapters/postgres.rb:314:in `block in execute'
  /disk5/www/gb/box/shared/bundle/ruby/2.5.0/gems/sequel-5.15.0/lib/sequel/connection_pool/threaded.rb:92:in `hold'
  /disk5/www/gb/box/shared/bundle/ruby/2.5.0/gems/sequel-5.15.0/lib/sequel/database/connecting.rb:270:in `synchronize'
  /disk5/www/gb/box/shared/bundle/ruby/2.5.0/gems/sequel-5.15.0/lib/sequel/adapters/postgres.rb:314:in `execute'
  /disk5/www/gb/box/shared/bundle/ruby/2.5.0/gems/sequel-5.15.0/lib/sequel/dataset/actions.rb:1083:in `execute'
  /disk5/www/gb/box/shared/bundle/ruby/2.5.0/gems/sequel-5.15.0/lib/sequel/adapters/postgres.rb:610:in `fetch_rows'
  /disk5/www/gb/box/shared/bundle/ruby/2.5.0/gems/sequel-5.15.0/lib/sequel/dataset/actions.rb:151:in `each'
  /disk5/www/gb/box/shared/bundle/ruby/2.5.0/gems/sequel_pg-1.11.0/lib/sequel_pg/sequel_pg.rb:81:in `each'
  /disk5/www/gb/box/shared/bundle/ruby/2.5.0/gems/sequel-5.15.0/lib/sequel/dataset/actions.rb:85:in `columns!'
  /disk5/www/gb/box/shared/bundle/ruby/2.5.0/gems/sequel-5.15.0/lib/sequel/dataset/actions.rb:75:in `columns'
  /disk5/www/gb/box/shared/bundle/ruby/2.5.0/gems/sequel-5.15.0/lib/sequel/model/base.rb:242:in `columns'
  /disk5/www/gb/box/shared/bundle/ruby/2.5.0/gems/sequel-auditer-0.1.0/lib/sequel/plugins/auditer.rb:118:in `block in configure'
  /disk5/www/gb/box/shared/bundle/ruby/2.5.0/gems/sequel-auditer-0.1.0/lib/sequel/plugins/auditer.rb:92:in `instance_eval'
  /disk5/www/gb/box/shared/bundle/ruby/2.5.0/gems/sequel-auditer-0.1.0/lib/sequel/plugins/auditer.rb:92:in `configure'
  /disk5/www/gb/box/shared/bundle/ruby/2.5.0/gems/sequel-5.15.0/lib/sequel/model/base.rb:550:in `plugin'
  /disk5/www/gb/box/releases/20181224143406/app/models/mailbox/email.rb:4:in `<class:Email>'
  /disk5/www/gb/box/releases/20181224143406/app/models/mailbox/email.rb:3:in `<module:Mailbox>'
  /disk5/www/gb/box/releases/20181224143406/app/models/mailbox/email.rb:2:in `<top (required)>'
  /disk5/www/gb/box/shared/bundle/ruby/2.5.0/gems/skylight-core-3.1.2/lib/skylight/core/probes.rb:119:in `require'
  /disk5/www/gb/box/shared/bundle/ruby/2.5.0/gems/skylight-core-3.1.2/lib/skylight/core/probes.rb:119:in `require'
  /disk5/www/gb/box/shared/bundle/ruby/2.5.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `block in require'
  /disk5/www/gb/box/shared/bundle/ruby/2.5.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:257:in `load_dependency'
  /disk5/www/gb/box/shared/bundle/ruby/2.5.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `require'
  /disk5/www/gb/box/shared/bundle/ruby/2.5.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:378:in `block in require_or_load'
  /disk5/www/gb/box/shared/bundle/ruby/2.5.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:37:in `block in load_interlock'
  /disk5/www/gb/box/shared/bundle/ruby/2.5.0/gems/activesupport-5.2.2/lib/active_support/dependencies/interlock.rb:14:in `block in loading'
  /disk5/www/gb/box/shared/bundle/ruby/2.5.0/gems/activesupport-5.2.2/lib/active_support/concurrency/share_lock.rb:151:in `exclusive'
  /disk5/www/gb/box/shared/bundle/ruby/2.5.0/gems/activesupport-5.2.2/lib/active_support/dependencies/interlock.rb:13:in `loading'
  /disk5/www/gb/box/shared/bundle/ruby/2.5.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:37:in `load_interlock'
  /disk5/www/gb/box/shared/bundle/ruby/2.5.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:356:in `require_or_load'
  /disk5/www/gb/box/shared/bundle/ruby/2.5.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:334:in `depend_on'
  /disk5/www/gb/box/shared/bundle/ruby/2.5.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:246:in `require_dependency'
  /disk5/www/gb/box/shared/bundle/ruby/2.5.0/gems/railties-5.2.2/lib/rails/engine.rb:478:in `block (2 levels) in eager_load!'
  /disk5/www/gb/box/shared/bundle/ruby/2.5.0/gems/railties-5.2.2/lib/rails/engine.rb:477:in `each'
  /disk5/www/gb/box/shared/bundle/ruby/2.5.0/gems/railties-5.2.2/lib/rails/engine.rb:477:in `block in eager_load!'
  /disk5/www/gb/box/shared/bundle/ruby/2.5.0/gems/railties-5.2.2/lib/rails/engine.rb:475:in `each'
  /disk5/www/gb/box/shared/bundle/ruby/2.5.0/gems/railties-5.2.2/lib/rails/engine.rb:475:in `eager_load!'
  /disk5/www/gb/box/shared/bundle/ruby/2.5.0/gems/railties-5.2.2/lib/rails/engine.rb:356:in `eager_load!'
  /disk5/www/gb/box/shared/bundle/ruby/2.5.0/gems/railties-5.2.2/lib/rails/application/finisher.rb:69:in `each'
  /disk5/www/gb/box/shared/bundle/ruby/2.5.0/gems/railties-5.2.2/lib/rails/application/finisher.rb:69:in `block in <module:Finisher>'
  /disk5/www/gb/box/shared/bundle/ruby/2.5.0/gems/railties-5.2.2/lib/rails/initializable.rb:32:in `instance_exec'
  /disk5/www/gb/box/shared/bundle/ruby/2.5.0/gems/railties-5.2.2/lib/rails/initializable.rb:32:in `run'
  /disk5/www/gb/box/shared/bundle/ruby/2.5.0/gems/railties-5.2.2/lib/rails/initializable.rb:61:in `block in run_initializers'
  /home/gencer/.rbenv/versions/2.5.3/lib/ruby/2.5.0/tsort.rb:228:in `block in tsort_each'
  /home/gencer/.rbenv/versions/2.5.3/lib/ruby/2.5.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
  /home/gencer/.rbenv/versions/2.5.3/lib/ruby/2.5.0/tsort.rb:431:in `each_strongly_connected_component_from'
  /home/gencer/.rbenv/versions/2.5.3/lib/ruby/2.5.0/tsort.rb:349:in `block in each_strongly_connected_component'
  /home/gencer/.rbenv/versions/2.5.3/lib/ruby/2.5.0/tsort.rb:347:in `each'
  /home/gencer/.rbenv/versions/2.5.3/lib/ruby/2.5.0/tsort.rb:347:in `call'
  /home/gencer/.rbenv/versions/2.5.3/lib/ruby/2.5.0/tsort.rb:347:in `each_strongly_connected_component'
  /home/gencer/.rbenv/versions/2.5.3/lib/ruby/2.5.0/tsort.rb:226:in `tsort_each'
  /home/gencer/.rbenv/versions/2.5.3/lib/ruby/2.5.0/tsort.rb:205:in `tsort_each'
  /disk5/www/gb/box/shared/bundle/ruby/2.5.0/gems/railties-5.2.2/lib/rails/initializable.rb:60:in `run_initializers'
  /disk5/www/gb/box/shared/bundle/ruby/2.5.0/gems/railties-5.2.2/lib/rails/application.rb:361:in `initialize!'
  /disk5/www/gb/box/releases/20181224143406/config/environment.rb:6:in `<top (required)>'
  config.ru:4:in `require_relative'
  config.ru:4:in `block in <main>'
  /disk5/www/gb/box/shared/bundle/ruby/2.5.0/gems/rack-2.0.6/lib/rack/builder.rb:55:in `instance_eval'
  /disk5/www/gb/box/shared/bundle/ruby/2.5.0/gems/rack-2.0.6/lib/rack/builder.rb:55:in `initialize'
  config.ru:1:in `new'
  config.ru:1:in `<main>'
  /disk5/www/gb/box/shared/bundle/ruby/2.5.0/gems/unicorn-5.4.1/lib/unicorn.rb:56:in `eval'
  /disk5/www/gb/box/shared/bundle/ruby/2.5.0/gems/unicorn-5.4.1/lib/unicorn.rb:56:in `block in builder'
  /disk5/www/gb/box/shared/bundle/ruby/2.5.0/gems/unicorn-5.4.1/lib/unicorn/http_server.rb:795:in `build_app!'
  /disk5/www/gb/box/shared/bundle/ruby/2.5.0/gems/unicorn-5.4.1/lib/unicorn/http_server.rb:139:in `start'
  /disk5/www/gb/box/shared/bundle/ruby/2.5.0/gems/unicorn-5.4.1/bin/unicorn:126:in `<top (required)>'
  /disk5/www/gb/box/shared/bundle/ruby/2.5.0/bin/unicorn:23:in `load'
  /disk5/www/gb/box/shared/bundle/ruby/2.5.0/bin/unicorn:23:in `<top (required)>'

```
Related issues: #74, #75 and #137.

**Comment by gencer** [comment]
@JonathanTron, two more questions:

I've monkey-patched (ugly) using initializer. Now everything works fine.

But, I still want to hear your idea. Actually, do you still support this gem? I see no improvements on issues for a while except one PR.

Thanks,
Gencer.

**Comment by JonathanTron** [comment]
Hi @gencer thanks for reporting the issue.

> Actually, do you still support this gem? I see no improvements on issues for a while except one PR.

Yes, I support the gem based on my usage. I currently have 3 fairly big Rails apps using it on production. So I fix issues reported when they are bugs, accept PR when they contain things I see I can continue to support in the futur, because I have limited time to work on this.

> Not quite correct but commenting/removing this line: https://github.com/TalentBox/sequel-rails/blob/master/lib/sequel_rails/sequel/database/active_support_notification.rb#L21
solves my problem. Simply I tell SequelRails to only log but not raise error.

I will need to investigate further because the ActiveSupport notifier is simply hooking (via ugly monkey-patching) in the `Sequel::Database#log_connection_yield` (see https://github.com/jeremyevans/sequel/blob/67cc4245227a6c01ecb20d0138aaf37b05a5aebc/lib/sequel/database/logging.rb#L37-L50). So I would expect that the `conn` given to this method is always the correct one as it is passed down by Sequel itself.

Can you give me more info on how you configure the multiple databases and define the models? A basic rails repo reproducing the issue would be best.

**Comment by gencer** [comment]
Hi @JonathanTron,

Thanks for replying my issue. I also believe that sample repo will be much more understandable. I will prepare an illustration one and update here as soon as possible. I'm currently on it. 

I will try with SQLite, if fails, i will try with PostgreSQL as mine if you're OK with this.

Glad that you are still working (even slightly) on this project.

Thanks,
Gencer.

**Comment by JonathanTron** [comment]
> I will try with SQLite, if fails, i will try with PostgreSQL as mine if you're OK with this.

Either is fine. From the error, it should not matter which database is used.

**Comment by gencer** [comment]
@JonathanTron, I remember now. It was working on `development`. However,i when I run my app on `production`, above errors shows up. I will re-try to reproduce on my end. Sorry for previous comment. (i've deleted it)

**Comment by gencer** [comment]
Well, well, and well.

I've found the traitor. :=)

It was my own gem that causes this problem. I will fix this on my own gem.

Issue fixed here. no need to do anything on SequelRails-side.

@JonathanTron, Sorry for few emails and making trouble there but at leas I heard news from you and know that project is very much alive.

Gencer.

**Comment by JonathanTron** [comment]
Glad you were finally able to pinpoint the problem.
