### ISSUE TITLE
NoMethodError: undefined method `logger' for nil:NilClass

### ISSUE THREAD

**Issue by ashish-infogain** [TalentBox/sequel-rails#191]
**I am using sequel-rails -1.2.0. In multiple rails application with sequel gem version(5.43.0). But when I am going to start the application or doing rake db:migrate then I am getting the above issue.**

here I found that the issue is coming from **lib/sequel_rails/railties/log_subscriber.rb:64**

`Caused by:
NoMethodError: undefined method `logger' for nil:NilClass
/home/travis/build/projectdx/es_indexer/vendor/bundle/ruby/2.5.0/gems/sequel-rails-1.2.0/lib/sequel_rails/railties/log_subscriber.rb:64:in `logger'
/home/travis/build/projectdx/es_indexer/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.8.1/lib/active_support/log_subscriber.rb:80:in `start'
/home/travis/build/projectdx/es_indexer/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.8.1/lib/active_support/notifications/fanout.rb:100:in `start'
/home/travis/build/projectdx/es_indexer/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.8.1/lib/active_support/notifications/fanout.rb:44:in `block in start'
/home/travis/build/projectdx/es_indexer/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.8.1/lib/active_support/notifications/fanout.rb:44:in `each'
/home/travis/build/projectdx/es_indexer/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.8.1/lib/active_support/notifications/fanout.rb:44:in `start'
/home/travis/build/projectdx/es_indexer/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.8.1/lib/active_support/notifications/instrumenter.rb:35:in `start'
/home/travis/build/projectdx/es_indexer/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.8.1/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
/home/travis/build/projectdx/es_indexer/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.8.1/lib/active_support/notifications.rb:168:in `instrument'
/home/travis/build/projectdx/es_indexer/vendor/bundle/ruby/2.5.0/gems/sequel-rails-1.2.0/lib/sequel_rails/sequel/database/active_support_notification.rb:11:in `log_connection_yield'`

**Comment by opensourceame** [comment]
For anyone still experiencing this, you can fix it like this:

`SequelRails.configuration = OpenStruct.new(logger: Logger.new($stdout))`
