### ISSUE TITLE
Can't start rails app anymore after following your instructions

### ISSUE THREAD

**Issue by Larivact** [TalentBox/sequel-rails#91]
```
C:/Ruby200/lib/ruby/gems/2.0.0/gems/railties-4.2.1/lib/rails/railtie/configuration.rb:95:in `method_missing': undefined method `active_record' for #<Rails::Application::Configuration:0x35c58c0> (NoMethodError)
        from C:/sequel-rails/config/application.rb:27:in `<class:Application>'
        from C:/sequel-rails/config/application.rb:13:in `<module:Most>'
        from C:/sequel-rails/config/application.rb:12:in `<top (required)>'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:78:in `require'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:78:in `block in server'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:75:in `tap'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:75:in `server'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/railties-4.2.1/lib/rails/commands.rb:17:in `<top (required)>'
        from bin/rails:4:in `require'
        from bin/rails:4:in `<main>'
```
ruby -v
ruby 2.0.0p645 (2015-04-13) [i386-mingw32]

rails -v
Rails 4.2.1

**Comment by JonathanTron** [comment]
Hi @Larivact, did you remove/commented out the line:

```ruby
# require "active_record/railtie"
```

in `config/application.rb`?

Is this a fresh app? Do you have anything relying on ActiveRecord in your app? Can you show your Gemfile?

**Comment by Larivact** [comment]
If I create a fresh app and replace ```require 'rails/all'``` with
```ruby
require "action_controller/railtie"
# require "active_record/railtie"
require "action_mailer/railtie"
require "sprockets/railtie"
```
in config/application.rb

and add ```gem "sequel-rails"``` to the Gemfile and do bundle install and then start the app I get the mentioned error.

**Comment by Larivact** [comment]
reproduced exactly the same under linux

ruby -v
ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-linux]

rails -v
Rails 4.2.1

**Comment by JonathanTron** [comment]
Ok I found it, after generating a new app and replacing the `require 'rails/all'`, there's still configuration of `active_record` related functionalities in those files:

```
config/application.rb
27:    config.active_record.raise_in_transactional_callbacks = true

config/environments/development.rb
23:  config.active_record.migration_error = :page_load

config/environments/production.rb
78:  config.active_record.dump_schema_after_migration = false
```

Remove or comment them and you should be fine.

I will add a comment about it in the README, thanks for reporting the issue.

**Comment by Larivact** [comment]
Great, it works! thanks, man :+1:
